import { VALIDATION_CODES } from "../codes.js";
import { SEVERITY } from "../severity.js";

export const categoryRules = {
  name: {
    field: "name",
    label: "Category Name",
    required: true,
    minLength: 2,
    maxLength: 80,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "Category name must be between 2 and 80 characters.",
    example: "Tulsi Malas & Necklaces",
    helperText: "Taxonomy display name.",
  },
  slug: {
    field: "slug",
    label: "Category Slug",
    required: true,
    minLength: 2,
    maxLength: 80,
    pattern: /^[a-z0-9-]+$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_SLUG,
    message: "Category slug must contain only lowercase letters, numbers, and hyphens.",
    example: "tulsi-malas",
    helperText: "URL slug for category page.",
    asyncCheck: "unique",
  },
  description: {
    field: "description",
    label: "Category Description",
    required: false,
    maxLength: 2000,
    severity: SEVERITY.WARNING,
    code: VALIDATION_CODES.FIELD_TOO_LONG,
    message: "Description should be under 2000 characters.",
    example: "Explore sacred Vrindavan Tulsi malas for daily chanting and meditation.",
  },
  emoji: {
    field: "emoji",
    label: "Emoji Icon",
    required: false,
    maxLength: 10,
    severity: SEVERITY.INFO,
    code: VALIDATION_CODES.FIELD_TOO_LONG,
    message: "Emoji icon string.",
    example: "📿",
  },
  h1: {
    field: "h1",
    label: "H1 Heading",
    required: false,
    maxLength: 100,
    severity: SEVERITY.WARNING,
    code: VALIDATION_CODES.FIELD_TOO_LONG,
    message: "H1 heading should be under 100 characters.",
    example: "Buy Original Sacred Tulsi Malas Online",
  },
};
