import { VALIDATION_CODES } from "../codes.js";
import { SEVERITY } from "../severity.js";

export const couponRules = {
  code: {
    field: "code",
    label: "Coupon Code",
    required: true,
    minLength: 3,
    maxLength: 20,
    pattern: /^[A-Z0-9_-]+$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.DUPLICATE_COUPON,
    message: "Coupon code must be 3-20 characters in uppercase (letters, numbers, hyphens).",
    example: "BHAKTI10",
    helperText: "Unique promo code entered at checkout.",
    asyncCheck: "unique",
  },
  type: {
    field: "type",
    label: "Discount Type",
    required: true,
    enum: ["percentage", "flat"],
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "Discount type must be either 'percentage' or 'flat'.",
    example: "percentage",
  },
  value: {
    field: "value",
    label: "Discount Value",
    required: true,
    min: 1,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PRICE,
    message: "Discount value must be greater than 0.",
    example: "10",
    helperText: "Percentage off (1-100) or flat amount in ₹.",
  },
  expiresAt: {
    field: "expiresAt",
    label: "Expiration Date",
    required: true,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.EXPIRED_DATE,
    message: "Expiration date is required and must be in the future.",
    example: "2026-12-31",
  },
  minOrderAmount: {
    field: "minOrderAmount",
    label: "Minimum Order Amount (₹)",
    required: false,
    min: 0,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PRICE,
    message: "Minimum order amount cannot be negative.",
    example: "499",
  },
  maxDiscount: {
    field: "maxDiscount",
    label: "Maximum Discount Limit (₹)",
    required: false,
    min: 1,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PRICE,
    message: "Maximum discount must be greater than 0 if specified.",
    example: "200",
  },
  usageLimit: {
    field: "usageLimit",
    label: "Usage Limit",
    required: false,
    min: 1,
    integerOnly: true,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_STOCK,
    message: "Usage limit must be a positive integer.",
    example: "100",
  },
};
