import { VALIDATION_CODES } from "../codes.js";
import { SEVERITY } from "../severity.js";

export const orderRules = {
  fullName: {
    field: "shippingAddress.fullName",
    label: "Full Name",
    required: true,
    minLength: 2,
    maxLength: 80,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "Full name is required (2-80 characters).",
    example: "Radha Sharma",
    helperText: "Recipient's complete name.",
  },
  phone: {
    field: "shippingAddress.phone",
    label: "Mobile Number",
    required: true,
    pattern: /^[6-9]\d{9}$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PHONE,
    message: "Valid 10-digit Indian mobile number required starting with 6, 7, 8, or 9.",
    example: "9876543210",
    helperText: "10-digit mobile number for delivery updates.",
  },
  line1: {
    field: "shippingAddress.line1",
    label: "Street Address",
    required: true,
    minLength: 5,
    maxLength: 120,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "Address line 1 must be between 5 and 120 characters.",
    example: "Flat 402, Shanti Kunj Apartments",
    helperText: "House/Flat number, building name, street.",
  },
  line2: {
    field: "shippingAddress.line2",
    label: "Address Line 2",
    required: false,
    maxLength: 120,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.FIELD_TOO_LONG,
    message: "Address line 2 cannot exceed 120 characters.",
    example: "Near ISKCON Temple Road",
  },
  landmark: {
    field: "shippingAddress.landmark",
    label: "Landmark (Optional)",
    required: false,
    maxLength: 120,
    severity: SEVERITY.INFO,
    code: VALIDATION_CODES.FIELD_TOO_LONG,
    message: "Landmark cannot exceed 120 characters.",
    example: "Opposite SBI Bank / Near Temple",
    helperText: "Nearby landmark for easy courier delivery.",
  },
  city: {
    field: "shippingAddress.city",
    label: "City",
    required: true,
    minLength: 2,
    maxLength: 60,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "City is required (2-60 characters).",
    example: "Vrindavan",
  },
  state: {
    field: "shippingAddress.state",
    label: "State",
    required: true,
    minLength: 2,
    maxLength: 60,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "State is required (2-60 characters).",
    example: "Uttar Pradesh",
  },
  pincode: {
    field: "shippingAddress.pincode",
    label: "PIN Code",
    required: true,
    pattern: /^\d{6}$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PINCODE,
    message: "Valid 6-digit Indian PIN code required.",
    example: "281121",
    helperText: "6-digit postal index number.",
  },
  email: {
    field: "email",
    label: "Email Address",
    required: true,
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_EMAIL,
    message: "Valid email address is required.",
    example: "radha@gmail.com",
    helperText: "Order confirmation receipt will be sent here.",
  },
};
