import { VALIDATION_CODES } from "../codes.js";
import { SEVERITY } from "../severity.js";

export const productRules = {
  name: {
    field: "name",
    label: "Product Name",
    required: true,
    minLength: 3,
    maxLength: 150,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.REQUIRED_FIELD,
    message: "Product name must be between 3 and 150 characters.",
    example: "Sacred Tulsi Kanthi Mala 108 Beads",
    helperText: "Enter a clear, descriptive title for the product.",
  },
  slug: {
    field: "slug",
    label: "URL Slug",
    required: true,
    minLength: 2,
    maxLength: 100,
    pattern: /^[a-z0-9-]+$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_SLUG,
    message: "Slug must contain only lowercase letters, numbers, and hyphens.",
    example: "sacred-tulsi-kanthi-mala-108-beads",
    helperText: "URL-friendly identifier. Auto-generated if left empty.",
    asyncCheck: "unique",
  },
  category: {
    field: "category",
    label: "Category ID",
    required: true,
    pattern: /^[0-9a-fA-F]{24}$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_MONGO_ID,
    message: "A valid Category must be selected.",
    example: "65f1a2b3c4d5e6f7a8b9c0d1",
    helperText: "Select the primary category for this product.",
  },
  categorySlug: {
    field: "categorySlug",
    label: "Category Slug",
    required: true,
    pattern: /^[a-z0-9-]+$/,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_SLUG,
    message: "Category slug is required.",
    example: "tulsi-malas",
  },
  basePrice: {
    field: "basePrice",
    label: "Base Price (₹)",
    required: true,
    min: 1,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PRICE,
    message: "Base price must be a positive number greater than 0.",
    example: "999",
    helperText: "Regular MRP price before discount.",
  },
  salePrice: {
    field: "salePrice",
    label: "Sale Price (₹)",
    required: false,
    min: 0,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_PRICE,
    message: "Sale price must be 0 or greater and cannot exceed Base Price.",
    example: "799",
    helperText: "Discounted selling price.",
  },
  stock: {
    field: "stock",
    label: "Inventory Stock",
    required: false,
    min: 0,
    integerOnly: true,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_STOCK,
    message: "Stock quantity must be a non-negative integer.",
    example: "50",
    helperText: "Available stock count.",
  },
  sku: {
    field: "sku",
    label: "SKU",
    required: false,
    pattern: /^[A-Za-z0-9_-]*$/,
    maxLength: 50,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_SKU,
    message: "SKU must contain only uppercase letters, numbers, hyphens, and underscores.",
    example: "NK-TUL-001",
    helperText: "Stock Keeping Unit identifier.",
    asyncCheck: "unique",
  },
  hsnCode: {
    field: "hsnCode",
    label: "HSN Code",
    required: false,
    pattern: /^[0-9]*$/,
    maxLength: 10,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_HSN,
    message: "HSN code must contain only numeric digits.",
    example: "71179090",
    helperText: "GST HSN/SAC code.",
  },
  gstRate: {
    field: "gstRate",
    label: "GST Rate (%)",
    required: false,
    min: 0,
    max: 100,
    severity: SEVERITY.ERROR,
    code: VALIDATION_CODES.INVALID_GST,
    message: "GST rate must be between 0% and 100%.",
    example: "3",
    helperText: "Applicable GST tax percentage.",
  },
  shortDescription: {
    field: "shortDescription",
    label: "Short Description",
    required: false,
    maxLength: 500,
    severity: SEVERITY.WARNING,
    code: VALIDATION_CODES.FIELD_TOO_LONG,
    message: "Short description should be under 500 characters for optimal card layout.",
    example: "Authentic 108-bead Tulsi mala handcrafted in Vrindavan.",
  },
};
