export const VALIDATION_CODES = {
  // Duplicate
  DUPLICATE_SLUG: "DUPLICATE_SLUG",
  DUPLICATE_SKU: "DUPLICATE_SKU",
  DUPLICATE_COUPON: "DUPLICATE_COUPON",
  DUPLICATE_CATEGORY_SLUG: "DUPLICATE_CATEGORY_SLUG",
  DUPLICATE_IMAGE_HASH: "DUPLICATE_IMAGE_HASH",

  // Format & Type
  INVALID_SLUG: "INVALID_SLUG",
  INVALID_SKU: "INVALID_SKU",
  INVALID_HSN: "INVALID_HSN",
  INVALID_PRICE: "INVALID_PRICE",
  INVALID_GST: "INVALID_GST",
  INVALID_STOCK: "INVALID_STOCK",
  INVALID_PINCODE: "INVALID_PINCODE",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_IMAGE: "INVALID_IMAGE",
  INVALID_MONGO_ID: "INVALID_MONGO_ID",
  INVALID_PRODUCT_ID: "INVALID_PRODUCT_ID",
  INVALID_URL: "INVALID_URL",

  // Length & Required
  REQUIRED_FIELD: "REQUIRED_FIELD",
  FIELD_TOO_SHORT: "FIELD_TOO_SHORT",
  FIELD_TOO_LONG: "FIELD_TOO_LONG",

  // Cross-field
  SALE_EXCEEDS_BASE: "SALE_EXCEEDS_BASE",
  COUPON_PERCENTAGE_EXCEEDS: "COUPON_PERCENTAGE_EXCEEDS",
  EXPIRED_DATE: "EXPIRED_DATE",

  // Image Analysis
  IMAGE_DIMENSION_TOO_SMALL: "IMAGE_DIMENSION_TOO_SMALL",
  IMAGE_CORRUPT: "IMAGE_CORRUPT",
  IMAGE_MISSING_ALT: "IMAGE_MISSING_ALT",
  IMAGE_ASPECT_RATIO_WARN: "IMAGE_ASPECT_RATIO_WARN",

  // SEO Analysis
  SEO_META_TITLE_LONG: "SEO_META_TITLE_LONG",
  SEO_META_DESC_LONG: "SEO_META_DESC_LONG",
  SEO_MISSING_H1: "SEO_MISSING_H1",
  SEO_KEYWORD_NOT_IN_TITLE: "SEO_KEYWORD_NOT_IN_TITLE",
  SEO_KEYWORD_NOT_IN_SLUG: "SEO_KEYWORD_NOT_IN_SLUG",

  // Entity Dependencies
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  RELATED_PRODUCT_NOT_FOUND: "RELATED_PRODUCT_NOT_FOUND",
  REQUIRED_PRIMARY_IMAGE_MISSING: "REQUIRED_PRIMARY_IMAGE_MISSING",
};
